# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

# theme                   : "minimal-mistakes-jekyll"
# remote_theme              : "mmistakes/minimal-mistakes"
minimal_mistakes_skin     : "dark" # "default" , "air", "aqua", "contrast", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                    : "ko-KR"
title                     : "닷커넥터의 지식과 경험의 발자국"
title_separator           : "-"
name                      : "김진관(닷커넥터)"
description               : "닷커넥터의 지식과 경험의 발자국"
url                       : "https://tigerjk9.github.io"
baseurl                   : # the subpath of your site, e.g. "/blog"
repository                : # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
logo                      : # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
masthead_title            : # overrides the website title displayed in the masthead, use " " for no title
words_per_minute          : 200

# ===================================================================
# Giscus 댓글 설정 (여기가 수정되었습니다)
# ===================================================================
comments:
  provider: "giscus"
  giscus:
    repo: "tigerjk9/tigerjk9.github.io"
    repo_id: "R_kgDOPyuEzg"
    category: "Comments"
    category_id: "DIC_kwDOPyuEzs4CxP6T"
    mapping: "specific-term"
    reactions_enabled: "1"
    emit_metadata: "0"
    input_position: "top"
    theme: "preferred_color_scheme"
    lang: "ko"
# ===================================================================

# SEO Related
google_site_verification    :
bing_site_verification      :
naver_site_verification     :
yandex_site_verification    :
baidu_site_verification     :

# Social Sharing
twitter:
  username                  :
facebook:
  username                  :
  app_id                    :
  publisher                 :
og_image                    : # Open Graph/Twitter default site image

# Analytics
analytics:
  provider                  : "google-gtag" # provider를 "google-gtag"로 변경
  google:
    tracking_id             : "G-Y8TNBPZQEZ" # 여기에 본인의 측정 ID 붙여넣기
    anonymize_ip            : false

# Site Author
author:
  name                      : "김진관(닷커넥터)"
  avatar                    : "/assets/jinkwan.png"
  bio                       : "배움, 나눔, 성장을 추구하는 연결주의자"
  location                  : #"대한민국 대전광역시"
  email                     : "faithfuljk@naver.com"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://linktr.ee/Dot_Connector"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://www.facebook.com/faithfuljk/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/tigerjk9/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/jinkwan_soul_groove/#"

# Site Structure
sidebar:
  - title: "Categories"
    html: sidebar/categories.html
  - title: "Tag Cloud"
    html: sidebar/tag_cloud.html
footer:
  links: [] # 이와 같이 links 목록을 비워줍니다.

# Reading Files
include:
  - .htaccess
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - minimal-mistakes-jekyll.gemspec
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: #

# Paginate
paginate: 10 # amount of posts to show
paginate_path: /page:num/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true # <-- 이 부분이 true여야 댓글이 보입니다 (이미 true로 잘 되어 있습니다)
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
